### ISSUE TITLE
Dodatkowe recepty do AgriCraft

### ISSUE THREAD

**Issue by Acerixx** [StarChasers/Testpack#21]
Przydadzą się 2 rośliny na Blizz Rod i Sulfur.
Blizz Rod potrzebuje Śniegu.
Sulfur lawę.

**Comment by marcin212** [comment]
Sulfur można uzyskać z 50% szansą z blaze rod-ów(można je hodować).
Blizz Rody nie są potrzebne, bo można hodować redstone i uzyskiwać śnieg.
