### ISSUE TITLE
[Forestry] Dark oak wogóle nie reaguje na krzyżowanie

### ISSUE THREAD

**Issue by Acerixx** [StarChasers/Testpack#23]
Próbuje skrzyżować Teak z Dark Oak ale nie pojawiają się żadne mutacje. Dark oak jest w wersji forestry. Może być też problem z Acacia, ale to tylko przypuszczenie.

**Comment by Acerixx** [comment]
Poprawa resin i sap w biogas engine jeśli chodzi o produkcje energii na tick. Produkcja 10 krotnie za niska.

**Comment by marcin212** [comment]
Jaka jest produkcja w rf?

**Comment by Acerixx** [comment]
sap 2 RF resin 3 RF

Dodatkowo draconic grafter nie daje sadzonek.

**Comment by marcin212** [comment]
jeden błąd jedno issue

**Comment by marcin212** [comment]
Dark oak  u mnie działa.
