### ISSUE TITLE
Błąd z produkcją energi w biogas engine [Binnie-Mods]

### ISSUE THREAD

**Issue by Acerixx** [StarChasers/Testpack#24]
Poprawa resin i sap w biogas engine jeśli chodzi o produkcje energii na tick. Produkcja 10 krotnie za niska.
Sap - 2 RF
Resin - 3 RF

**Comment by marcin212** [comment]
https://bitbucket.org/binnie567/binnie-mods/issue/148/sap-and-resin-in-biogas-engine-give-10

**Comment by marcin212** [comment]
fixed

**Comment by marcin212** [comment]
fixed
