### ISSUE TITLE
Grafter nie daje sadzonek [Forestry Extras 2]

### ISSUE THREAD

**Issue by Acerixx** [StarChasers/Testpack#25]
Problem występuje z Draconic grafter i Reinforced grafter.

**Comment by marcin212** [comment]
@alucard87pl 
W forestry grafter ma ustawioną szansę na 100. Natomiast draconic grafter i reinforced grafter mają ustawione na 1,5 i 2,0. Tak powinno być czy to jest błąd? (Sadzonki prawie nie wypadają)

**Comment by alucard87pl** [comment]
@marcin212 
In Forestry, the grafter has the drop chance set to 100. But the draconic and reinforced grafters have their drop chance set to 1.5 and 2.0 respectively. Is that by design, or is this a bug? (saplings almost never drop)

**Comment by marcin212** [comment]
https://github.com/wasliebob/FE2/issues/2

**Comment by marcin212** [comment]
już daje sadzonki ale nie z 100% szansą
