### ISSUE TITLE
Extra cells is breaking my tanks. [Thermal Expansion-ExtraCells]

### ISSUE THREAD

**Issue by cola98765** [StarChasers/Testpack#30]
When i use a portable tank[TE] to move fluid from me chest[AE] with fluid storage[EC] the tank fills up, but when i try to place the tank it disappears.

**Comment by marcin212** [comment]
@cola98765 Raczej naprawione przetestuj i daj znać

**Comment by cola98765** [comment]
Dziala. Zamykam issue.
