### ISSUE TITLE
Forestry i trade station

### ISSUE THREAD

**Issue by serekk11** [StarChasers/Testpack#33]
Klikam prawym na trade station  z dowolnym przedmiotem w ręku,  i wyrzuca mnie z gry.

logs:
https://gist.github.com/serekk11/9e75f4ac7ea3bd892096

**Comment by Acerixx** [comment]
Mam to samo. Przyczyną jest klikniecie PPM z itemem (np. obsydian) na trade station.

**Comment by marcin212** [comment]
@alucard87pl 
Problem pojawia się najprawdopodobniej po restarcie serwer z tradestation które nie zostały nazwane(postawione i nigdy nie otworzone). Crashuje klienta po kliknięciu prawym.

**Comment by alucard87pl** [comment]
@marcin212 
The problem occurs most probably after a server restart if there are unclaimed Trade Stations (placed, but never opened). The client crashes when they are right-clicked.

**Comment by marcin212** [comment]
https://github.com/ForestryMC/ForestryMC/issues/518

**Comment by marcin212** [comment]
fixed
