### ISSUE TITLE
[Thermal Expansion] Nie wyświetla się ilośc prądu w celce

### ISSUE THREAD

**Issue by marcin212** [StarChasers/Testpack#37]
@alucard87pl 
Nie wyświetla się ilość prądu w celce powyżej 50mln(pewnie ze względu na zmieniony rozmiar).
Testowałem z nowo wycraftowanymi.
https://dl.dropboxusercontent.com/u/25172450/bugs/bugs1710/8081ef23c876f6026257b61672217601.png

**Comment by alucard87pl** [comment]
@marcin212 
Stored energy amount does not display properly, if it is above 50 million (probably due to the increase in capacity)
Tested with freshly crafted cell.
[link]

**Comment by marcin212** [comment]
fixed
