### ISSUE TITLE
[OC] Bug monitora

### ISSUE THREAD

**Issue by Acerixx** [StarChasers/Testpack#41]
Po wyłączeniu jednostki centralnej monitor zapamiętuje ostatni stan wyświetlania i pobiera energie. Zniszczenie monitora naprawia go.

**Comment by asiekierka** [comment]
To nie blad, to wynika z tego ze kazda czesc komputera to oddzielne urzadzenie.

Temat zamykam, uzyj opcji "szukaj".

**Comment by marcin212** [comment]
Wyłączaj komputer za pomocą odpowiedniego polecenia.
