### ISSUE TITLE
[NEW][IE - RC] brak compatybilnosci butelek z creosote oilem

### ISSUE THREAD

**Issue by cola98765** [StarChasers/Testpack#52]
trzeba dodac do oredicta

**Comment by marcin212** [comment]
Piec produkuje tylko te z railcarafta. Jak uzyskałeś w jakiś sposób butelki z IE to napisz jak

**Comment by cola98765** [comment]
spawn we wioskach

**Comment by cola98765** [comment]
inaczej. mamy ten z RC ale w recepcie z IE wymagany jest z IE

**Comment by marcin212** [comment]
Te z IE można zamieninić na te z railcrafta w craftingu. Dodałem też brakujacą receptę.
