### ISSUE TITLE
zawieszajacy sie cache z hoperem

### ISSUE THREAD

**Issue by Acerixx** [StarChasers/Testpack#6]
podczas przesypywania z cache do drugiego cache przez hoper po jakimś czasie przestaje przesyłać itemy do hopera.
http://puu.sh/e1GLZ/8cdf1e8921.png

**Comment by cola98765** [comment]
mam taki problem tez z rurami z bc podlaczonymi bezposrednio do cachea

**Comment by marcin212** [comment]
fixed
