### ISSUE TITLE
[New][IE]straty pradu na rozstajach

### ISSUE THREAD

**Issue by cola98765** [StarChasers/Testpack#63]
basic setup (MV cables set in config for 2048RF/t)
![2015-07-10_13 58 19](https://cloud.githubusercontent.com/assets/10381827/8618288/dd42a764-270c-11e5-854c-af98ff8467ee.png)
on single connection everything is looking fine
![2015-07-10_14 12 58](https://cloud.githubusercontent.com/assets/10381827/8618381/f943df0e-270d-11e5-98cc-1836939845cc.png)
![2015-07-10_14 18 46](https://cloud.githubusercontent.com/assets/10381827/8618442/85c89cc6-270e-11e5-9a12-6c8eab64978d.png)
power loses
![2015-07-10_13 58 54](https://cloud.githubusercontent.com/assets/10381827/8618286/dd413bfe-270c-11e5-92dd-c21c0aeaba25.png)
50% efficiency
![2015-07-10_14 05 48](https://cloud.githubusercontent.com/assets/10381827/8618289/dd4513c8-270c-11e5-93eb-027f7af21177.png)

**Comment by marcin212** [comment]
fixed
