### ISSUE TITLE
[Feature request]Cassette Tapes on Bibliocraft Disc Racks?

### ISSUE THREAD

**Issue by alucard87pl** [StarChasers/Testpack#71]
Turns out, BiblioCraft already has a config option for that, as mentioned here:
https://github.com/asiekierka/Computronics/issues/143#issuecomment-122727550

> Add "tape" to the `S:AdditionalDiscs` list in the BiblioCraft config, now you can store tapes on a disc rack.

**Comment by marcin212** [comment]
dodane podczas wczorajszej aktualizacji.

**Comment by alucard87pl** [comment]
:heart: :heart: :heart:
